"use client";

import { useSignal } from "@/lib/hooks/useStockData";

const ACTION_STYLES: Record<string, string> = {
  BUY: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  SELL: "bg-red-500/15 text-red-400 border-red-500/30",
  HOLD: "bg-slate-500/15 text-slate-300 border-slate-500/30",
};

export function SignalPanel({ symbol }: { symbol: string }) {
  const { data, isLoading, error } = useSignal(symbol);

  if (isLoading) {
    return <PanelShell>Loading signal…</PanelShell>;
  }

  if (error) {
    return (
      <PanelShell>
        <p className="text-red-400 text-sm">{(error as Error).message}</p>
      </PanelShell>
    );
  }

  if (!data) return null;

  const { signal } = data;

  return (
    <PanelShell>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-sm font-medium text-slate-400 uppercase tracking-wide">
          Signal
        </h2>
        <span
          className={`px-3 py-1 rounded-full text-sm font-semibold border ${ACTION_STYLES[signal.action]}`}
        >
          {signal.action}
        </span>
      </div>

      {signal.conflicting && (
        <div className="mb-3 px-3 py-2 rounded bg-amber-500/10 border border-amber-500/30 text-amber-400 text-xs">
          Technical and sentiment signals disagree — confidence suppressed
        </div>
      )}

      <div className="grid grid-cols-2 gap-3 mb-4 text-sm">
        <Stat label="Confidence" value={`${Math.round(signal.confidence * 100)}%`} />
        <Stat label="Volatility" value={signal.risk.volatilityRegime} />
        <Stat label="Entry" value={`$${signal.risk.entryPrice.toFixed(2)}`} />
        <Stat label="R:R" value={`1:${signal.risk.riskRewardRatio}`} />
        <Stat label="Stop Loss" value={`$${signal.risk.stopLoss.toFixed(2)}`} accent="text-red-400" />
        <Stat label="Take Profit" value={`$${signal.risk.takeProfit.toFixed(2)}`} accent="text-emerald-400" />
      </div>

      <div className="border-t border-slate-800 pt-3">
        <h3 className="text-xs font-medium text-slate-500 uppercase tracking-wide mb-2">
          Rationale
        </h3>
        <ul className="space-y-1">
          {signal.rationale.map((line, i) => (
            <li key={i} className="text-xs text-slate-400">
              {line}
            </li>
          ))}
        </ul>
      </div>

      <p className="mt-4 text-[11px] text-slate-600 leading-relaxed">
        This signal is generated by a rules-based model combining technical
        indicators and news sentiment. It is not financial advice — verify
        independently before making any trading decision.
      </p>
    </PanelShell>
  );
}

function Stat({ label, value, accent }: { label: string; value: string; accent?: string }) {
  return (
    <div>
      <div className="text-slate-500 text-xs">{label}</div>
      <div className={`font-medium ${accent ?? "text-slate-200"}`}>{value}</div>
    </div>
  );
}

function PanelShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">{children}</div>
  );
}
